from api.v1.views.courses import *
from api.v1.views.departments import *
from api.v1.views.assingments import *
from api.v1.views.communications import *
from api.v1.views.materials import *
from api.v1.views.roles_n_admins import *
from api.v1.views.scores import *
from api.v1.views.students import *
from api.v1.views.submissions import *
from api.v1.views.teachers import *
from api.v1.views.degrees import *
from api.v1.views.teacher_dept import *
from api.v1.views.teacher_course import *
