"""initial commit

Revision ID: 4f16b4427c1c
Revises: 
Create Date: 2024-09-14 19:59:18.834561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f16b4427c1c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('tel', sa.String(), nullable=False),
    sa.Column('citizenship', sa.String(), nullable=False),
    sa.Column('last_login', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('degrees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('degree_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('degree_name')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('tel', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('citizenship', sa.String(), nullable=False),
    sa.Column('staff_member', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('courses',
    sa.Column('course_code', sa.String(), nullable=False),
    sa.Column('course_name', sa.String(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('year_of_study', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['admins.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('course_code'),
    sa.UniqueConstraint('course_name')
    )
    op.create_table('departments',
    sa.Column('dept_code', sa.String(), nullable=False),
    sa.Column('dept_name', sa.String(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('trimester_or_semester', sa.String(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('n_teachers', sa.Integer(), nullable=True),
    sa.Column('hod', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hod'], ['teachers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('dept_code'),
    sa.UniqueConstraint('dept_name')
    )
    op.create_table('roles_admin',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('date_granted', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teachers_degree',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('degree_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['degree_id'], ['degrees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('dept_id', sa.String(), nullable=False),
    sa.Column('course_id', sa.String(), nullable=False),
    sa.Column('assign_title', sa.String(), nullable=False),
    sa.Column('year_of_study', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_code'], ),
    sa.ForeignKeyConstraint(['dept_id'], ['departments.dept_code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('communications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('dept_id', sa.String(), nullable=False),
    sa.Column('year_of_study', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['dept_id'], ['departments.dept_code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('department_course',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dept_id', sa.String(), nullable=False),
    sa.Column('course_id', sa.String(), nullable=False),
    sa.Column('date_assigned', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dept_id'], ['departments.dept_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('materials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_code', sa.String(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('year_of_study', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['course_code'], ['courses.course_code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('regno', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('tel', sa.String(), nullable=False),
    sa.Column('dept_id', sa.String(), nullable=False),
    sa.Column('year_of_study', sa.Integer(), nullable=False),
    sa.Column('sponsorship', sa.String(), nullable=False),
    sa.Column('citizenship', sa.String(), nullable=False),
    sa.Column('last_login', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['dept_id'], ['departments.dept_code'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('regno'),
    sa.UniqueConstraint('email')
    )
    op.create_table('teacher_courses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('course_code', sa.String(), nullable=False),
    sa.Column('date_assigned', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['course_code'], ['courses.course_code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teacher_departments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('dept_id', sa.String(), nullable=False),
    sa.Column('date_assigned', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['dept_id'], ['departments.dept_code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('material_department',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.String(), nullable=False),
    sa.Column('date_uploaded', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.dept_code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('dept_id', sa.String(), nullable=False),
    sa.Column('course_code', sa.String(), nullable=False),
    sa.Column('assign_score', sa.Integer(), nullable=True),
    sa.Column('cat_score', sa.Integer(), nullable=True),
    sa.Column('exam_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_code'], ['courses.course_code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dept_id'], ['departments.dept_code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.regno'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_code', sa.String(), nullable=False),
    sa.Column('dept_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('assign_id', sa.Integer(), nullable=False),
    sa.Column('year_of_study', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['assign_id'], ['assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_code'], ['courses.course_code'], ),
    sa.ForeignKeyConstraint(['dept_id'], ['departments.dept_code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.regno'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submissions')
    op.drop_table('scores')
    op.drop_table('material_department')
    op.drop_table('teacher_departments')
    op.drop_table('teacher_courses')
    op.drop_table('students')
    op.drop_table('materials')
    op.drop_table('department_course')
    op.drop_table('communications')
    op.drop_table('assignments')
    op.drop_table('teachers_degree')
    op.drop_table('roles_admin')
    op.drop_table('departments')
    op.drop_table('courses')
    op.drop_table('teachers')
    op.drop_table('roles')
    op.drop_table('degrees')
    op.drop_table('admins')
    # ### end Alembic commands ###
