"""reducing redundacny

Revision ID: 78479808b7da
Revises: ad41e3d1434c
Create Date: 2024-09-16 12:38:43.871818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78479808b7da'
down_revision = 'ad41e3d1434c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.drop_column('year_of_study')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_of_study', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
