"""changing student nullable field

Revision ID: ad41e3d1434c
Revises: 4f16b4427c1c
Create Date: 2024-09-14 22:59:20.967130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad41e3d1434c'
down_revision = '4f16b4427c1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('sponsorship',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('sponsorship',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
