"""
03RD FEB 2024
WHAT IS COMPLETED
    -> ADMIN AND ROLES RELATIONSHIP COMPLETED
    -> COURSE AND DEPARTMENTS RELATIONSHIP COMPLETED
    -> TEACHERS AND DEGREES RELATIONSHIPS COMPLETED

    
04TH FEB 2024
WHAT IS ON AGENDA
    ->TEACHER AND COURSE RELATIONSHIP COMPLETED
    ->TEACHER AND MATERIALS REALATIONSHIP COMPLETED
    ->TEACHER AND DEGRESS RELATIONSHIP COMPLETED


WHAT DONE PARTIALLY WITHOUT RELATIONSHIP HANDLED
    -> ASSIGNMENT TABLE --- WITH TEACHER AND STUDENTS
"""

"""
UNDONE BY TODAY NIGHT 04 FEB 2024

COMMUNICATION TABLE
SCHEDULES TABLE
STUDENTS TABLE
SUBMISSIONS TABLE
"""
